# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# Service definition file for an eris:db chain.
# Requires Version (handled by eris-cli).

[service]
image          = "quay.io/eris/erisdb:version"
data_container = true
ports          = [ "1337", "46656", "46657" ]
entry_point    = "erisdb-wrapper"

[dependencies]
services = [ "keys" ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"
